# -*- coding: utf-8 -*-
"""add_pubchem_logP-mp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IgvHp_ShKJTzV3Xj0jfxfnWPDR-z4Av
"""

import pandas as pd
cbio3 = pd.read_csv('SolCbio3Database_merged.csv')
mp = pd.read_csv('mp_pubchem.csv')
logp = pd.read_csv('logp_pubchem.csv')

cbio3_missing_mp = cbio3[cbio3['mp'].isnull()].copy()
cbio3_missing_logp = cbio3[cbio3['logPN'].isnull()].copy()

is_present_mp = cbio3_missing_mp['SMILES_standard'].isin(logp['SMILES_standard'])
is_present_logp = cbio3_missing_logp['SMILES_standard'].isin(logp['SMILES_standard'])

cbio3_missing_logp_with_logp = cbio3_missing_logp[is_present_logp].copy()
merged_logp = pd.merge(cbio3_missing_logp_with_logp[['SMILES_standard']],
                       logp[['SMILES_standard']],
                       on='SMILES_standard',
                       how='left')

cbio3.loc[cbio3_missing_logp_with_logp.index, 'Ref_logP'] = "PubChem"

cbio3.loc[cbio3_missing_logp_with_logp.index]

cbio3_missing_mp_with_mp = cbio3_missing_mp[is_present_mp].copy()
merged_mp = pd.merge(cbio3_missing_mp_with_mp[['SMILES_standard']],
                       mp[['SMILES_standard']],
                       on='SMILES_standard',
                       how='left')

cbio3.loc[cbio3_missing_mp_with_mp.index, 'Ref_mp'] = "PubChem"

cbio3.loc[cbio3_missing_mp_with_mp.index]

cbio3.to_csv('SolCbio3Database_merged2.csv')

