# -*- coding: utf-8 -*-
"""morgan_fingerprint_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiM4jpCIRBBQyWHF9HlaZ1ulNJd2xGC3
"""

import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem

def _morgan_fp_single_mol(mol):
    """
    Generates Morgan fingerprints for a single RDKit molecule object.
    This is an internal helper function.
    """
    if mol is None:
        return None  # Handle cases where mol conversion failed
    morgan = AllChem.GetMorganGenerator(radius=2, fpSize=1024)
    return morgan.GetFingerprint(mol)

def generate_morgan_fingerprints(smiles_list):
    """
    Transforms a list of SMILES codes into a DataFrame of Morgan fingerprints.

    Args:
        smiles_list (list): A list of SMILES strings.

    Returns:
        pd.DataFrame: A DataFrame where each row corresponds to a SMILES string
                      and columns are the 1024 Morgan fingerprint bits, prefixed
                      with 'morgan_fp_'. Returns an empty DataFrame if no valid
                      SMILES codes are processed.
    """
    if not isinstance(smiles_list, list):
        raise TypeError("Input must be a list of SMILES strings.")

    # Create RDKit Mol objects from SMILES, handling invalid SMILES by returning None
    mols = [Chem.MolFromSmiles(s) for s in smiles_list]

    # Generate Morgan fingerprints, filtering out None for invalid molecules
    fingerprints_with_nones = [_morgan_fp_single_mol(mol) for mol in mols]

    # Keep track of original SMILES for valid entries if needed, here we just filter
    valid_fingerprints = [fp for fp in fingerprints_with_nones if fp is not None]

    if not valid_fingerprints:
        print("Warning: No valid SMILES codes were processed into fingerprints.")
        return pd.DataFrame()  # Return empty DataFrame if no valid fingerprints

    # Convert RDKit ExplicitBitVect objects to lists of integers
    fingerprint_lists = [list(fp) for fp in valid_fingerprints]

    # Create a new DataFrame from these lists, which will automatically create 1024 columns
    morgan_expanded_df = pd.DataFrame(fingerprint_lists)

    # Add 'morgan_fp_' prefix to the new column names
    morgan_expanded_df = morgan_expanded_df.add_prefix('morgan_fp_')

    return morgan_expanded_df

# Example usage (demonstrates how the function works if run directly)
if __name__ == "__main__":
    print("Running example for morgan_fingerprint_generator.py...")
    test_smiles = [
        "CCC",
        "CCO",
        "CC(=O)Oc1ccccc1C(=O)O",  # Aspirin
        "INVALID_SMILES",       # Example of an invalid SMILES
        "NCCC(CCO)C(=O)O"
    ]

    fingerprint_df = generate_morgan_fingerprints(test_smiles)
    print("\nGenerated Morgan Fingerprint DataFrame (first 5 rows):")
    if not fingerprint_df.empty:
        print(fingerprint_df.head())
        print(f"Shape of generated DataFrame: {fingerprint_df.shape}")
    else:
        print("No fingerprints generated due to invalid SMILES or empty input.")