# -*- coding: utf-8 -*-
"""standard_smiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjaJsFx2I7MvWE39QJ37q29EJwANeHCi
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install molvs
# !pip install rdkit

from molvs import standardize_smiles
from rdkit import Chem
import pandas as pd

cas = pd.read_csv('SolCbio3Database_merged.csv', engine='python', on_bad_lines='warn')

cas

def is_valid_smiles(smiles):
    """Checks if a SMILES string can be parsed by RDKit."""
    if pd.isna(smiles):
        return False # Treat NaN as invalid
    return Chem.MolFromSmiles(str(smiles), sanitize=True) is not None

# Create a boolean mask indicating valid SMILES
valid_smiles_mask_cas = cas['smiles'].apply(is_valid_smiles)


# Filter the dataframe to keep only rows with valid SMILES
cas_cleaned = cas[valid_smiles_mask_cas].copy()

# Display the first few rows of the cleaned dataframe and the number of rows removed

print(f"Number of rows removed from cas: {len(cas) - len(cas_cleaned)}")

cas_cleaned['SMILES_standard'] = cas_cleaned['smiles'].astype(str).apply(lambda x: standardize_smiles(x))

cas_cleaned.to_csv('SolCbio3Database_merged_2.csv')

#from google.colab import files
#files.download('CAS_pubchem.csv')